http://localhost:3000

###

http://localhost:3000/getAll

###

http://localhost:3000/add
content-type: application/json

{
    "todo": "limpiar la habitacion"
}

###

http://localhost:3000/delete/jkfXYcU6zRqL2yVyIa_Ez

###

http://localhost:3000/update/Ax1iY5ID_LRa_Eh8uSJR0
content-type: application/json

{
    "text": "limpiar la casa"
}

###

http://localhost:3000/do/wEXGEWOXfd-riLNCLbi0W
content-type: application/json

###


http://localhost:3000/undo/1
content-type: application/json

###